src/Frontend/Jp.UI.SSO/Models/RedirectViewModel.cs
namespace Jp.UI.SSO.Models
{
    public class RedirectViewModel
    {
        public string RedirectUrl { get; set; }
    }
}

src/Frontend/Jp.UI.SSO/Controllers/Diagnostics/DiagnosticsController.cs
// Copyright (c) Brock Allen & Dominick Baier. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.


using JPProject.Sso.Application.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;

namespace Jp.UI.SSO.Controllers.Diagnostics
{
    [Authorize]
    public class DiagnosticsController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IGlobalConfigurationAppService _globalConfigurationAppService;

        public DiagnosticsController(IConfiguration configuration, IGlobalConfigurationAppService globalConfigurationAppService)
        {
            _configuration = configuration;
            _globalConfigurationAppService = globalConfigurationAppService;
        }
        public async Task<IActionResult> Index()
        {
            //var localAddresses = new string[] { "127.0.0.1", "::1", HttpContext.Connection.LocalIpAddress.ToString() };
            //if (!localAddresses.Contains(HttpContext.Connection.RemoteIpAddress.ToString()))
            //{
            //    return NotFound();
            //}
            var model = new DiagnosticsViewModel(HttpContext, await HttpContext.AuthenticateAsync(), _configuration);
            return View(model);
        }
    }
}

src/Frontend/Jp.UI.SSO/Controllers/Grants/GrantsController.cs
// Copyright (c) Brock Allen & Dominick Baier. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.


using IdentityServer4.Events;
using IdentityServer4.Extensions;
using IdentityServer4.Services;
using IdentityServer4.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jp.UI.SSO.Controllers.Grants
{
    /// <summary>
    /// This sample controller allows a user to revoke grants given to clients
    /// </summary>
    [Authorize]
    public class GrantsController : Controller
    {
        private readonly IIdentityServerInteractionService _interaction;
        private readonly IClientStore _clients;
        private readonly IResourceStore _resources;
        private readonly IEventService _events;

        public GrantsController(IIdentityServerInteractionService interaction,
            IClientStore clients,
            IResourceStore resources,
            IEventService events)
        {
            _interaction = interaction;
            _clients = clients;
            _resources = resources;
            _events = events;
        }

        /// <summary>
        /// Show list of grants
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("Index", await BuildViewModelAsync());
        }

        /// <summary>
        /// Handle postback to revoke a client
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Revoke(string clientId)
        {
            await _interaction.RevokeUserConsentAsync(clientId);
            await _events.RaiseAsync(new GrantsRevokedEvent(User.GetSubjectId(), clientId));
            return RedirectToAction("Index");
        }

        private async Task<GrantsViewModel> BuildViewModelAsync()
        {
            var grants = await _interaction.GetAllUserConsentsAsync();

            var list = new List<GrantViewModel>();
            foreach (var grant in grants)
            {
                var client = await _clients.FindClientByIdAsync(grant.ClientId);
                if (client != null)
                {
                    var resources = await _resources.FindResourcesByScopeAsync(grant.Scopes);

                    var item = new GrantViewModel()
                    {
                        ClientId = client.ClientId,
                        ClientName = client.ClientName ?? client.ClientId,
                        ClientLogoUrl = client.LogoUri,
                        ClientUrl = client.ClientUri,
                        Created = grant.CreationTime,
                        Expires = grant.Expiration,
                        IdentityGrantNames = resources.IdentityResources.Select(x => x.DisplayName ?? x.Name).ToArray(),
                        ApiGrantNames = resources.ApiResources.Select(x => x.DisplayName ?? x.Name).ToArray()
                    };

                    list.Add(item);
                }
            }

            return new GrantsViewModel
            {
                Grants = list
            };
        }
    }
}

src/Frontend/Jp.UI.SSO/Views/Shared/Redirect.cshtml
@model Jp.UI.SSO.Models.RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="@Url.Content("~/js/signin-redirect.js")"></script>

src/Frontend/Jp.UI.SSO/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@using Jp.UI.SSO.Util
@{
    string name = null;
    string image = null;
    if (Context.User.IsAuthenticated())
    {
        name = Context.User?.GetDisplayName();
        image = Context.User?.Claims.FirstOrDefault(a => a.Type == "picture")?.Value ?? "~/images/no-image.png";
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="JP Project - Open Source IdentityServer4 Admin">
    <meta name="author" content="Bruno Brito">
    <meta name="keyword" content="ID4,IdentityServer4,AdminUI,UserManagement,Open,Source,MicroService,Identity,SSO">
    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' http://* 'unsafe-inline'; script-src 'self' http://* 'unsafe-inline' 'unsafe-eval'" />
    <title>JP Project - Open Source IdentityServer4 Admin</title>
    <!-- Icons-->
    <link href="@Url.Content("~/css/jp.min.css")" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/images/favicon/apple-touch-icon.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/images/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/images/favicon/favicon-16x16.png")">
    <link rel="manifest" href="@Url.Content("~/images/favicon/site.webmanifest.json")">
    <link rel="mask-icon" href="@Url.Content("~/images/favicon/safari-pinned-tab.svg")" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    @*<script asp-append-version="true" crossorigin="anonymous" src="~/js/app.insights.js"></script>*@
</head>
<body>
    <div class="bg-marketing text-center text-white p-3">
        💪💪💪 Please help us on Github. Give us a star ⭐️ 🙏🙏 ➡
        <iframe src="https://ghbtns.com/github-btn.html?user=brunohbrito&repo=JPProject.IdentityServer4.SSO&type=star" frameborder="0" scrolling="0" width="160px" height="20px"></iframe>
    </div>
    <div class="app sidebar-fixed footer-fixed aside-menu-fixed">
        <header class="app-header navbar">
            <a class="navbar-brand" href="#">
                <div class="d-none d-lg-block">
                    <img class="navbar-brand-full logo-min" src="@Url.Content("~/images/brand/logo.png")" alt="JP Logo">
                    <img class="navbar-brand-minimized" src="@Url.Content("~/images/brand/logo.png")" width="40" alt="JP Logo">
                </div>
                <div class="d-lg-none text-left">
                    <img class="navbar-brand-full" src="@Url.Content("~/images/brand/logo-min.png")" height="40" alt="JP Logo">
                    <img class="navbar-brand-minimized" src="@Url.Content("~/images/brand/logo-min.png")" width="40" alt="JP Logo">
                </div>
            </a>
            <ul class="nav navbar-nav ml-auto">
                @await Html.PartialAsync("_SelectLanguagePartial")
                <li class="nav-item dropdown">
                    <a class="nav-link d-none d-md-block" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <img class="img-avatar" src="@Url.Content(image)" alt="@name">@name
                    </a>
                    <a class="nav-link d-md-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <img class="img-avatar" src="@Url.Content(image)" alt="@name">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header text-center">
                            <strong>Account</strong>
                        </div>
                        <a class="dropdown-item"
                           asp-action="Index"
                           asp-controller="Grants">
                            <i class="fa fa-tasks"></i>
                            <span>Grants</span>
                        </a>

                        <a class="dropdown-item"
                           asp-action="Logout"
                           asp-controller="Account">
                            <i class="fa fa-lock"></i> Logout
                        </a>
                        <div class="dropdown-header text-center">
                            <strong>Settings</strong>
                        </div>
                        <a class="dropdown-item"
                           asp-action="Index"
                           asp-controller="Diagnostics">
                            <i class="fa fa-server"></i>
                            <span>Diagnostic</span>
                        </a>
                    </div>
                </li>
            </ul>

        </header>

        <div class="app-body">
            <main class="main">
                @RenderSection("breadcrumb", false)
                @RenderBody()
            </main>
        </div>
        <footer class="app-footer">
            <div>
                <a href="https://github.com/brunohbrito/JP-Project" target="_blank"><img class="icon logo-min" src="@Url.Content("~/images/brand/logo.png")"></a>&nbsp;
                <span>@SsoVersion.Current &copy; 2018.</span>
            </div>
            <div class="ml-auto">
                <span>Powered by</span>
                <a href="https://coreui.io">CoreUI</a>
            </div>
        </footer>
    </div>
    <script src="@Url.Content("~/js/jp.min.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Frontend/Jp.UI.SSO/Views/Shared/_LayoutExt.cshtml
@using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="JP Project - Open Source IdentityServer4 Admin">
    <meta name="author" content="Bruno Brito">
    <meta name="keyword" content="ID4,IdentityServer4,AdminUI,UserManagement,Open,Source,MicroService,Identity,SSO">
    <title>JP Project - Open Source IdentityServer4 Admin</title>
    <!-- Icons-->
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/images/favicon/apple-touch-icon.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/images/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/images/favicon/favicon-16x16.png")">
    <link rel="manifest" href="@Url.Content("~/images/favicon/site.webmanifest.json")">
    <link rel="mask-icon" href="@Url.Content("~/images/favicon/safari-pinned-tab.svg")" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="@Url.Content("~/css/jp.min.css")" rel="stylesheet">
    @*<script asp-append-version="true" crossorigin="anonymous" src="~/js/app.insights.js"></script>*@
</head>
<body>
    <div class="bg-marketing text-center text-white p-3">
        💪💪💪 Please help us on Github. Give us a star ⭐️ 🙏🙏 ➡
        <iframe src="https://ghbtns.com/github-btn.html?user=brunohbrito&repo=JP-Project&type=star" frameborder="0" scrolling="0" width="160px" height="20px"></iframe>
    </div>
    <div class="app flex-row align-items-center">
        <div class="container-fluid">
            <div class="animated fadeIn">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="@Url.Content("~/js/jp.min.js")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Frontend/Jp.UI.SSO/Views/Shared/_ScopeListItem.cshtml
@using Jp.UI.SSO.Controllers.Consent
@model Jp.UI.SSO.Controllers.Consent.ScopeViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<li class="list-group-item list-group-item-info">
    <div class="form-group row">
        <div class="col-md-3 col-sm-3 col-lg-2">
            <label class="switch switch-label switch-success">
                <input class="switch-input" type="checkbox"
                       name="ScopesConsented"
                       id="scopes_@Model.Name"
                       value="@Model.Name"
                       checked="@Model.Checked"
                       disabled="@Model.Required">
                <span class="switch-slider" data-checked="On" data-unchecked="Off"></span>
            </label>
        </div>
        <div class="col-9 text-left">
            <label for="scopes_@Model.Name">
                @if (Model.Required)
                {
                    <input type="hidden"
                           name="ScopesConsented"
                           value="@Model.Name" />
                }
                <strong>@Model.DisplayName</strong>
                @if (Model.Emphasize)
                {
                    <i class="fa fa-exclamation-circle"></i>
                }
            </label>

            @if (Model.Required)
            {
                <span><em>@Localizer["Body-(required)"]</em></span>
            }
            @if (Model.Description != null)
            {
                <div class="consent-description">
                    <label for="scopes_@Model.Name">@Model.Description</label>
                </div>
            }
        </div>
    </div>
</li>

src/Frontend/Jp.UI.SSO/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-2x fa-globe"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
            <strong>@Localizer["Title-Available-Languages"]</strong>
        </div>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="pt-BR" class="dropdown-item">
            <i class="flag-icon flag-icon-br"></i> Portuguese (Brazil)
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="en" class="dropdown-item">
            <i class="flag-icon flag-icon-us"></i> English
        </a>

        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="el-GR" class="dropdown-item">
            <i class="flag-icon flag-icon-gr"></i> Greek
        </a>

        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="es" class="dropdown-item">
            <i class="flag-icon flag-icon-es"></i> Spanish
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="fr" class="dropdown-item">
            <i class="flag-icon flag-icon-fr"></i> French
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="nl" class="dropdown-item">
            <i class="flag-icon flag-icon-nl"></i> Dutch
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="ru" class="dropdown-item">
            <i class="flag-icon flag-icon-ru"></i> Russian
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="zh-cn" class="dropdown-item">
            <i class="flag-icon flag-icon-cn"></i> Chinese Simplified
        </a>
        <a asp-controller="Home" asp-action="SetLanguage" asp-route-culture="zh-tw" class="dropdown-item">
            <i class="flag-icon flag-icon-cn"></i> Chinese Traditional
        </a>
    </div>
</li>

src/Frontend/Jp.UI.SSO/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}